# By nikitSwaraj
---
- hosts: webservers
  sudo: yes
  remote_user: root
  tasks: 
      - name: Updating System
        apt: name=* state=latest
        #      - name: Install EPEL-repo
        #yum: name=epel-release state=latest
        #- name: Install nginx
        #yum: name=nginx state=latest
        #- name: start the service
        #service: name=nginx state=started
